export const products = [
  {
    id: "1",
    name: "Shrimp",
    description: "Prefers to live in pairs",
    price: 19,
    currency: "€",
  },
  {
    id: "2",
    name: "Anemonefish",
    description: "Nemo",
    price: 65,
    currency: "€",
  },
  {
    id: "3",
    name: "Splendid anemone",
    description: "Is splendid",
    price: 90,
    currency: "€",
  },
  {
    id: "4",
    name: "Killer mussel",
    description: "Is prettier than her name",
    price: 12,
    currency: "€",
  },
  {
    id: "5",
    name: "Angelfish",
    description: "A diurnal loner",
    price: 90,
    currency: "€",
  },
  {
    id: "6",
    name: "Guppy",
    description: "Small but nice",
    price: 5,
    currency: "€",
  },
  {
    id: "7",
    name: "Rainbow fish",
    description: "In all colors",
    price: 12,
    currency: "€",
  },
];
